"""project key

Revision ID: 4fc30360a775
Revises: 80a6cde3f407
Create Date: 2025-07-16 10:19:55.745082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc30360a775'
down_revision = '80a6cde3f407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('project_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_key', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
